//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class KHENTHUONGKYLUAT
    {
        public int IdKhenThuongKyLuat { get; set; }
        public string SoKhenThuongKyLuat { get; set; }
        public string NoiDung { get; set; }
        public Nullable<System.DateTime> NgayQuyetDinh { get; set; }
        public Nullable<int> MaNV { get; set; }
        public string LoaiKhenThuongKyLuat { get; set; }
        public string LyDo { get; set; }
        public Nullable<System.DateTime> NgayBatDau { get; set; }
        public Nullable<System.DateTime> NgayKetThuc { get; set; }
    
        public virtual NHANVIEN NHANVIEN { get; set; }
    }
}
