//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class NHANVIEN_LUONG
    {
        public int IdNhanVienLuong { get; set; }
        public int MaNV { get; set; }
        public int BacLuong { get; set; }
        public Nullable<double> KhoanCong { get; set; }
        public Nullable<double> KhoanTru { get; set; }
        public string LyDoCong { get; set; }
        public string LyDoTru { get; set; }
        public Nullable<double> ThucLinh { get; set; }
    
        public virtual LUONG LUONG { get; set; }
        public virtual NHANVIEN NHANVIEN { get; set; }
    }
}
